package com.bjsp123.rl2.model;

public class World {
    public Level[] levels;
    public int currentLevelIndex;
    /** Monotonic game-turn counter. Incremented once per render-frame in which any game
     *  state advanced, giving every game event a consistent time stamp across level
     *  changes. Used by {@code HistoricalRecord} to time-stamp history entries. */
    public int turn;
    /** Monotonic <b>game-tick</b> counter — the finer-grained currency drained by
     *  {@link com.bjsp123.rl2.logic.TurnSystem#tick(Level)}. Persisted across level
     *  changes. */
    public int tick;
    /** Tracks unique-content ids that have already been generated somewhere in the
     *  world — referenced at level-generation time so unique rooms / mobs / items
     *  never appear twice in the same run. */
    public UniqueTracker unique = new UniqueTracker();

    /** World-generation seed. Stored so the same dungeon can be regenerated by
     *  passing this value back through {@link WorldTopology#build}, and shown to
     *  the player as a six-letter code via
     *  {@link com.bjsp123.rl2.util.SeedCode#encode(long)}. */
    public long seed;

    public World() {}

    public World(Level[] levels) {
        this.levels = levels;
        this.currentLevelIndex = 0;
    }

    public Level currentLevel() {
        return levels[currentLevelIndex];
    }

    /** Wire each non-null level's transient back-reference to {@code this}.
     *  Called once after construction (so freshly-built worlds resolve
     *  inter-level references like the chasm-fall-through-floor mechanic
     *  via {@link Level#world}) and again on save load (after JSON
     *  deserialisation drops the transient field). */
    public void linkLevels() {
        if (levels == null) return;
        for (Level l : levels) if (l != null) l.world = this;
    }
}
