package com.bjsp123.rl2.ai.game;

import com.bjsp123.rl2.event.GameEvent;
import com.bjsp123.rl2.logic.CombatArena;
import com.bjsp123.rl2.logic.GameBalance;
import com.bjsp123.rl2.logic.MobFactory;
import com.bjsp123.rl2.model.Level;
import com.bjsp123.rl2.model.Mob;
import com.bjsp123.rl2.model.Point;
import com.bjsp123.rl2.model.Tile;
import com.bjsp123.rl2.model.UniqueTracker;
import com.bjsp123.rl2.model.World;
import com.bjsp123.rl2.model.WorldTopology;

import java.util.Random;

/**
 * One full-game autoplay run: a {@link World} generated by {@link WorldTopology},
 * a SMART-piloted agent dropped at depth 1, and a tick loop that lets
 * {@link com.bjsp123.rl2.ai.SmartAi} drive every action. Each tick walks
 * {@link Level#events} for {@link GameEvent.ItemPickedUp} and
 * {@link GameEvent.MobKilled} and reconciles {@link World#currentLevelIndex}
 * deltas to keep {@link AutoplayStats} current.
 */
public final class AutoplayGame {

    public enum Outcome { IN_PROGRESS, DEATH, TIMEOUT, WIN }

    public final World world;
    public final Mob agent;
    public final AutoplayStats stats = new AutoplayStats();
    public final long seed;
    public Outcome outcome = Outcome.IN_PROGRESS;
    public int turnsElapsed;

    private int lastLevelIndex;
    /** When non-null, per-tick warrior-stuck telemetry is accumulated and
     *  written to a per-run summary file at run end. Independent of the
     *  per-decision trace CSV pipeline. */
    private StuckTelemetry stuck;
    /** When non-null, every SmartAi decision is written as a CSV row here. */
    private java.io.PrintWriter traceWriter;
    /** When non-null, every game event involving the agent is written here. */
    private java.io.PrintWriter eventsWriter;
    /** When non-null, combat decisions and damage events go here. */
    private java.io.PrintWriter combatWriter;
    private Point lastTracePosition;

    private AutoplayGame(World world, Mob agent, long seed) {
        this.world = world;
        this.agent = agent;
        this.seed = seed;
        this.lastLevelIndex = world.currentLevelIndex;
        stats.ensureSizedFor(world.levels.length);
        stats.maxDepth = world.levels.length - 1;
    }

    /**
     * Build a fresh world, spawn a SMART-behavior player of the given class on
     * the entry level, and place them on a walkable tile. Caller must have
     * already called {@link com.bjsp123.rl2.ai.RaiBootstrap#init()} so the
     * SMART brain is registered.
     */
    public static AutoplayGame newRun(long seed, Mob.CharacterClass cls,
                                      int worldW, int worldH) {
        // Pin every process-wide gameplay RNG (combat / AI / environment) to
        // this run's seed so the whole sim replays deterministically - same
        // seed, same run. World-gen already seeds its own local rng below.
        com.bjsp123.rl2.util.SimRng.reseedAll(seed);
        Random rng = new Random(seed);
        World world = new World();
        world.unique = new UniqueTracker();
        world.seed   = seed;
        world.levels = WorldTopology.build(worldW, worldH, rng, world.unique);
        world.currentLevelIndex = 0;
        for (Level lvl : world.levels) lvl.world = world;

        Level start = world.currentLevel();
        Point spawn = pickSpawn(start, rng);
        Mob agent = MobFactory.player(spawn, cls);
        agent.behavior = Mob.Behavior.SMART;
        agent.stateOfMind = Mob.StateOfMind.AWAKE;
        start.mobs.add(agent);
        return new AutoplayGame(world, agent, seed);
    }

    /** Enable warrior-stuck telemetry: per-level dwell / decision mix /
     *  bombs+wands+melee effectiveness summarised to
     *  {@code autoplay-stuck-<class>-<seed>.log}. Independent of trace CSV. */
    public void enableStuckLog() {
        try {
            stuck = new StuckTelemetry(agent, seed);
            System.out.println("[autoplay-stuck] writing autoplay-stuck-"
                    + agent.mobType + "-" + seed + ".log");
            installDecisionHook();
        } catch (java.io.IOException e) {
            System.err.println("[autoplay-stuck] open failed: " + e.getMessage());
            stuck = null;
        }
    }

    /** Install the SmartAi decision hook once, regardless of which output
     *  mode (trace / stuck) requested it. The hook updates lastStepName
     *  unconditionally and forwards to writeTraceRow only when the CSV
     *  writer is open. */
    private void installDecisionHook() {
        com.bjsp123.rl2.ai.SmartAi.setDecisionTraceHook(this::onDecision);
    }

    private void onDecision(Mob m, com.bjsp123.rl2.ai.WorldState state,
                            com.bjsp123.rl2.ai.action.Action step) {
        if (m == agent && step != null) lastStepName = step.name();
        if (traceWriter != null) writeTraceRow(m, state, step);
    }

    /** Enable per-decision tracing for this run. Opens
     *  {@code autoplay-trace-<class>-<seed>.csv} immediately and writes one row
     *  per SmartAi decision until the run ends. Header is written immediately. */
    public void enableDecisionTrace() {
        try {
            String name = "autoplay-trace-" + agent.mobType + "-" + seed + ".csv";
            java.nio.file.Path p = java.nio.file.Paths.get(name).toAbsolutePath();
            traceWriter = new java.io.PrintWriter(java.nio.file.Files.newBufferedWriter(p));
            traceWriter.println("tick,levelIdx,agentX,agentY,posChanged,ticksTillMove,"
                    + "moveCost,branch,action,actionDetail,"
                    + "hp,maxHp,visEnemies,nearestEnemyDist,lastSeenTile,buffs,bagSummary,"
                    + "tileHere,vegetationHere,surfaceHere,fireRemainingHere,"
                    + "knownFraction,exploreTarget,bfsStepFrontier,stairsDown,bfsStepStairs,"
                    + "targetPosition");
            traceWriter.flush();

            String evName = "autoplay-events-" + agent.mobType + "-" + seed + ".csv";
            java.nio.file.Path evp = java.nio.file.Paths.get(evName).toAbsolutePath();
            eventsWriter = new java.io.PrintWriter(java.nio.file.Files.newBufferedWriter(evp));
            eventsWriter.println("tick,levelIdx,eventType,detail");
            eventsWriter.flush();

            String cbName = "autoplay-combat-" + agent.mobType + "-" + seed + ".csv";
            java.nio.file.Path cbp = java.nio.file.Paths.get(cbName).toAbsolutePath();
            combatWriter = new java.io.PrintWriter(java.nio.file.Files.newBufferedWriter(cbp));
            combatWriter.println("tick,levelIdx,kind,playerHp,playerMaxHp,playerCharLvl,"
                    + "targetType,targetCharLvl,targetHp,targetMaxHp,targetDist,visibleEnemies,"
                    + "chosenAction,chosenIntent,chosenUtility,equippedWeapon,"
                    + "candidateCount,allCandidates,damageAmount,damageElement");
            combatWriter.flush();

            System.out.println("[autoplay-trace] writing " + p);
            System.out.println("[autoplay-events] writing " + evp);
            System.out.println("[autoplay-combat] writing " + cbp);
            installDecisionHook();
        } catch (java.io.IOException e) {
            System.err.println("[autoplay-trace] open failed: " + e.getMessage());
            traceWriter = null;
            eventsWriter = null;
        }
    }

    private void writeTraceRow(Mob m, com.bjsp123.rl2.ai.WorldState state,
                               com.bjsp123.rl2.ai.action.Action step) {
        if (traceWriter == null || m != agent) return;
        Level level = world.currentLevel();
        com.bjsp123.rl2.ai.MobMemory mem = state.memory;
        int ax = m.position == null ? -1 : m.position.tileX();
        int ay = m.position == null ? -1 : m.position.tileY();
        boolean posChanged = lastTracePosition == null
                ? true
                : (lastTracePosition.tileX() != ax || lastTracePosition.tileY() != ay);
        lastTracePosition = m.position;
        StringBuilder buffs = new StringBuilder();
        if (m.buffs != null) {
            for (var b : m.buffs) {
                if (b == null || b.type == null) continue;
                if (buffs.length() > 0) buffs.append("|");
                buffs.append(b.type.name()).append("(").append(b.stacks).append(")");
            }
        }
        String tileHere = ax >= 0 && ay >= 0 && ax < level.width && ay < level.height
                ? level.tiles[ax][ay].name() : "-";
        String vegHere = (level.vegetation != null && ax >= 0 && ay >= 0
                && ax < level.width && ay < level.height
                && level.vegetation[ax][ay] != null)
                ? level.vegetation[ax][ay].name() : "-";
        String surfHere = (level.surface != null && ax >= 0 && ay >= 0
                && ax < level.width && ay < level.height
                && level.surface[ax][ay] != null)
                ? level.surface[ax][ay].name() : "-";
        int fireHere = (level.fireRemaining != null && ax >= 0 && ay >= 0
                && ax < level.width && ay < level.height)
                ? level.fireRemaining[ax][ay] : 0;
        int bagPotion = 0, bagBomb = 0, bagFood = 0, bagTool = 0,
                bagWeapon = 0, bagArmor = 0, bagOther = 0;
        if (m.inventory != null && m.inventory.bag != null) {
            for (var it : m.inventory.bag) {
                if (it == null || it.inventoryCategory == null) continue;
                int n = Math.max(1, it.count);
                switch (it.inventoryCategory) {
                    case POTION -> bagPotion += n;
                    case BOMB   -> bagBomb   += n;
                    case FOOD   -> bagFood   += n;
                    case TOOL   -> bagTool   += n;
                    case WEAPON, OFFHAND -> bagWeapon += n;
                    case ARMOR  -> bagArmor  += n;
                    default     -> bagOther  += n;
                }
            }
        }
        double knownFrac = mem == null
                ? 0.0
                : 1.0 - com.bjsp123.rl2.ai.eval.ExplorationEval.unexploredFraction(level, mem);
        Point exploreT = mem == null
                ? null
                : com.bjsp123.rl2.ai.eval.ExplorationEval.nearestExploreTarget(m, level, mem);
        Point bfsToFront = exploreT == null
                ? null
                : com.bjsp123.rl2.ai.eval.ExplorationEval.nextStepToTarget(m, level, mem, exploreT);
        Point bfsToStairs = level.stairsDown == null
                ? null
                : com.bjsp123.rl2.ai.eval.ExplorationEval.nextStepToTarget(m, level, mem, level.stairsDown);
        traceWriter.printf("%d,%d,%d,%d,%s,%d,%d,%s,%s,%s,%.1f,%.0f,%d,%d,%s,%s,P=%d;B=%d;F=%d;T=%d;W=%d;A=%d;X=%d,%s,%s,%s,%d,%.3f,%s,%s,%s,%s,%s%n",
                turnsElapsed, world.currentLevelIndex,
                ax, ay, posChanged ? "Y" : "N",
                m.ticksTillMove, m.effectiveStats().moveCost,
                com.bjsp123.rl2.ai.Decider.LAST_BRANCH.get(),
                step == null ? "-" : step.name(),
                step == null ? "-" : safeCsv(step.intentDetail()),
                m.hp, m.effectiveStats().maxHp,
                state.visibleEnemies.size(),
                state.nearestEnemyDist == Integer.MAX_VALUE ? -1 : state.nearestEnemyDist,
                state.lastKnownEnemyTile == null ? "-"
                        : state.lastKnownEnemyTile.tileX() + ":" + state.lastKnownEnemyTile.tileY(),
                buffs.length() == 0 ? "-" : buffs.toString(),
                bagPotion, bagBomb, bagFood, bagTool, bagWeapon, bagArmor, bagOther,
                tileHere, vegHere, surfHere, fireHere,
                knownFrac,
                exploreT == null ? "-" : exploreT.tileX() + ":" + exploreT.tileY(),
                bfsToFront == null ? "null" : bfsToFront.tileX() + ":" + bfsToFront.tileY(),
                level.stairsDown == null ? "-"
                        : level.stairsDown.tileX() + ":" + level.stairsDown.tileY(),
                bfsToStairs == null ? "null"
                        : bfsToStairs.tileX() + ":" + bfsToStairs.tileY(),
                m.targetPosition == null ? "-"
                        : m.targetPosition.tileX() + ":" + m.targetPosition.tileY());
        traceWriter.flush();

        // Combat-log: dump details whenever the decision was a fight or flee
        // action. The Decider's LAST_CANDIDATES holds the per-tick candidate
        // list with utility scores.
        if (combatWriter != null) {
            String branch = com.bjsp123.rl2.ai.Decider.LAST_BRANCH.get();
            if ("fight".equals(branch) || "flee".equals(branch)) {
                writeCombatRow(m, state, step, branch);
            }
        }
    }

    private void writeCombatRow(Mob m, com.bjsp123.rl2.ai.WorldState state,
                                com.bjsp123.rl2.ai.action.Action step, String branch) {
        Level level = world.currentLevel();
        // Pick the most relevant target: nearest visible enemy.
        Mob target = state.nearestEnemy;
        String tType = target == null ? "-" : target.mobType;
        int tLvl   = target == null ? 0 : target.characterLevel;
        double tHp = target == null ? 0 : target.hp;
        double tMaxHp = target == null ? 0 : target.effectiveStats().maxHp;
        int tDist  = target == null ? -1 : state.nearestEnemyDist;
        // Identify the weapon used for the chosen action: melee uses the equipped
        // weapon, throws/wand/grapple/charge name the item in their intent detail.
        String weapon = "-";
        if (step != null) {
            switch (step.name()) {
                case "melee" -> {
                    if (m.inventory != null && m.inventory.weapon != null) {
                        weapon = m.inventory.weapon.type;
                    } else {
                        weapon = "FISTS";
                    }
                }
                case "throw", "wand", "grapple", "charge", "drink", "jump" -> {
                    weapon = step.intentDetail() == null ? "-"
                            : safeCsv(step.intentDetail());
                }
                default -> { weapon = "-"; }
            }
        }
        // All candidates with utility.
        StringBuilder cands = new StringBuilder();
        var list = com.bjsp123.rl2.ai.Decider.LAST_CANDIDATES.get();
        for (var c : list) {
            if (cands.length() > 0) cands.append(";");
            cands.append(c.name())
                 .append("(")
                 .append(c.applicable() ? String.format("%.3f", c.utility()) : "n/a")
                 .append(")");
        }
        combatWriter.printf("%d,%d,%s,%.1f,%.0f,%d,%s,%d,%.1f,%.0f,%d,%d,%s,%s,%s,%s,%d,%s,,%n",
                turnsElapsed, world.currentLevelIndex, "DECISION",
                m.hp, m.effectiveStats().maxHp, m.characterLevel,
                tType, tLvl, tHp, tMaxHp, tDist,
                state.visibleEnemies.size(),
                step == null ? "-" : step.name(),
                step == null ? "-" : safeCsv(step.intentDetail()),
                step == null ? "-" : findChosenUtility(step, list),
                weapon,
                list.size(),
                safeCsv(cands.toString()));
        combatWriter.flush();
    }

    private static String findChosenUtility(com.bjsp123.rl2.ai.action.Action step,
                                             java.util.List<com.bjsp123.rl2.ai.Decider.CandidateScore> list) {
        for (var c : list) {
            if (c.name().equals(step.name())
                    && java.util.Objects.equals(c.detail(), step.intentDetail())) {
                return String.format("%.3f", c.utility());
            }
        }
        return "-";
    }

    private static String safeCsv(String s) {
        return s == null ? "-" : s.replace(',', ';').replace('\n', ' ');
    }

    /** Reflectively summarise a GameEvent: type + record-component values. Lets
     *  us see every event without enumerating every concrete subtype. Filters
     *  to events likely to involve the agent (buff applications, fire spread,
     *  damage, etc.) - but for the diagnostic we log everything. */
    private void writeEvent(GameEvent ev, int depthIdx) {
        if (ev == null) return;
        String type = ev.getClass().getSimpleName();
        // Mirror combat-relevant events (damage / kills / heals) to combat-log.
        if (combatWriter != null) {
            switch (type) {
                case "DamageDealt", "MobKilled", "HealApplied", "PeriodicBuffDamage" ->
                        writeCombatEventRow(ev, type, depthIdx);
                default -> { /* skip */ }
            }
        }
        StringBuilder detail = new StringBuilder();
        // GameEvent subclasses are records; iterate their components.
        var components = ev.getClass().getRecordComponents();
        if (components != null) {
            for (int i = 0; i < components.length; i++) {
                if (i > 0) detail.append("|");
                detail.append(components[i].getName()).append("=");
                try {
                    Object v = components[i].getAccessor().invoke(ev);
                    detail.append(formatVal(v));
                } catch (Exception e) {
                    detail.append("?");
                }
            }
        }
        eventsWriter.printf("%d,%d,%s,%s%n", turnsElapsed, depthIdx, type,
                safeCsv(detail.toString()));
    }

    /** Read amount + target/source from a GameEvent via reflection and write a
     *  combat-log row. Stays generic so we don't have to know each event's
     *  exact record layout. */
    private void writeCombatEventRow(GameEvent ev, String type, int depthIdx) {
        var comps = ev.getClass().getRecordComponents();
        Mob attacker = null, victim = null;
        int amount = 0;
        String element = "-";
        if (comps != null) {
            for (var c : comps) {
                try {
                    Object v = c.getAccessor().invoke(ev);
                    String n = c.getName();
                    if (v instanceof Mob m) {
                        if ("attacker".equals(n) || "killer".equals(n) || "source".equals(n)) attacker = m;
                        else if ("target".equals(n) || "victim".equals(n) || "mob".equals(n)) victim = m;
                    } else if (v instanceof Number num) {
                        if ("amount".equals(n) || "damage".equals(n)) amount = num.intValue();
                    } else if (v != null && "element".equals(n)) {
                        element = v.toString();
                    }
                } catch (Exception ignored) { }
            }
        }
        String victimType = victim == null ? "-" : victim.mobType;
        double victimHp = victim == null ? 0 : victim.hp;
        double victimMax = victim == null ? 0 : victim.effectiveStats().maxHp;
        boolean playerInvolved = (attacker == agent || victim == agent);
        if (!playerInvolved && !"MobKilled".equals(type)) return;
        combatWriter.printf("%d,%d,%s,%.1f,%.0f,%d,%s,%d,%.1f,%.0f,-,-,-,-,-,-,-,-,%d,%s%n",
                turnsElapsed, depthIdx, type,
                agent.hp, agent.effectiveStats().maxHp, agent.characterLevel,
                victimType,
                victim == null ? 0 : victim.characterLevel,
                victimHp, victimMax,
                amount, element);
        combatWriter.flush();
    }

    private static String formatVal(Object v) {
        if (v == null) return "null";
        if (v instanceof com.bjsp123.rl2.model.Mob m) {
            return (m.mobType != null ? m.mobType : "mob")
                    + "@" + (m.position == null ? "?"
                            : m.position.tileX() + ":" + m.position.tileY())
                    + ";hp=" + (int) m.hp;
        }
        if (v instanceof com.bjsp123.rl2.model.Item it) {
            return it.type;
        }
        if (v instanceof com.bjsp123.rl2.model.Point p) {
            return p.tileX() + ":" + p.tileY();
        }
        return v.toString();
    }

    /** Scan every level / every mob / every bag for a CATCHERBALL-style
     *  item whose {@code capturedMob} field holds the agent. Returns a
     *  short description naming the holder and level, or "-" if none. */
    private String capturingItemDesc(com.bjsp123.rl2.model.World w) {
        if (w == null || w.levels == null) return "-";
        for (int li = 0; li < w.levels.length; li++) {
            Level lvl = w.levels[li];
            if (lvl == null) continue;
            if (lvl.items != null) {
                for (com.bjsp123.rl2.model.Item it : lvl.items) {
                    if (it != null && it.capturedMob == agent) {
                        return it.type + "@floor lvl=" + li;
                    }
                }
            }
            if (lvl.mobs != null) {
                for (com.bjsp123.rl2.model.Mob m : lvl.mobs) {
                    if (m == null || m.inventory == null || m.inventory.bag == null) continue;
                    for (com.bjsp123.rl2.model.Item it : m.inventory.bag) {
                        if (it != null && it.capturedMob == agent) {
                            return it.type + "@" + m.mobType + " bag lvl=" + li;
                        }
                    }
                }
            }
        }
        return "-";
    }

    /** Advance one tick. Returns true if the run is still in progress. */
    public boolean tick(int dtMs) {
        if (outcome != Outcome.IN_PROGRESS) return false;
        Level cur = world.currentLevel();
        if (stuck != null) stuck.onTickStart(turnsElapsed);
        CombatArena.tickHeadless(cur, world, dtMs);
        turnsElapsed++;
        // Re-read the current level after the tick: stairs, chasm-fall, and
        // teleport scatter all migrate the agent to a different level and
        // update world.currentLevelIndex. Without this refresh the local cur
        // still points to the level we LEFT, so cur.mobs.contains(agent) would
        // be false and the death check below would misfire even though the
        // agent is happily alive on the new level.
        cur = world.currentLevel();
        observeEvents(cur);
        observeStairs();
        if (stuck != null) recordStuckTick(cur);
        // Death detection: hp <= 0 OR the agent was removed from the current
        // level's mob list (kill paths in rlib call level.mobs.remove without
        // necessarily clamping hp; a corpse with positive hp from a late REGEN
        // tick would otherwise keep the run "alive" while the agent is actually
        // gone).
        if (agent.hp <= 0 || !cur.mobs.contains(agent)) {
            // Diagnostic: if the agent is gone from the current level but
            // still alive, find where it ended up and dump enough context to
            // identify the silent removal path. This shouldn't fire after the
            // transferMobToLevel refactor; if it does, there's still another
            // mob.remove(agent) path leaking.
            if (agent.hp > 0) {
                int foundIdx = -1;
                if (world.levels != null) {
                    for (int li = 0; li < world.levels.length; li++) {
                        Level lvl = world.levels[li];
                        if (lvl != null && lvl.mobs != null && lvl.mobs.contains(agent)) {
                            foundIdx = li;
                            break;
                        }
                    }
                }
                System.out.println("[autoplay] WARN agent silently removed alive"
                        + " hp=" + agent.hp
                        + " curIdx=" + world.currentLevelIndex
                        + " foundIdx=" + foundIdx
                        + " pos=" + (agent.position == null ? "null"
                                : agent.position.tileX() + "," + agent.position.tileY())
                        + " capturedBy=" + capturingItemDesc(world));
            }
            finish(Outcome.DEATH);
            return false;
        }
        if (world.currentLevelIndex >= world.levels.length - 1
                && stats.depthReached >= world.levels.length - 1) {
            finish(Outcome.WIN);
            return false;
        }
        return true;
    }

    /** Drive {@link #tick(int)} until done or {@code tickBudget} ticks have passed. */
    public AutoplayStats runUntil(int tickBudget) {
        for (int i = 0; i < tickBudget && outcome == Outcome.IN_PROGRESS; i++) {
            tick(16);
        }
        if (outcome == Outcome.IN_PROGRESS) finish(Outcome.TIMEOUT);
        return stats;
    }

    /* ---------- internals ---------- */

    private void finish(Outcome o) {
        if (traceWriter != null) { traceWriter.close(); traceWriter = null; }
        if (eventsWriter != null) { eventsWriter.close(); eventsWriter = null; }
        if (combatWriter != null) { combatWriter.close(); combatWriter = null; }
        if (stuck != null) {
            stuck.close(o.name(), turnsElapsed, world.currentLevelIndex,
                    Math.max(stats.depthReached, world.currentLevelIndex));
            stuck = null;
        }
        com.bjsp123.rl2.ai.SmartAi.setDecisionTraceHook(null);
        outcome = o;
        stats.outcome = o.name();
        stats.turnsSurvived = turnsElapsed;
        stats.depthReached = Math.max(stats.depthReached, world.currentLevelIndex);
        stats.finalHp = Math.max(0, agent.hp);
        stats.finalMaxHp = agent.effectiveStats().maxHp;
        stats.finalCharLevel = agent.characterLevel;
        int perksSum = 0;
        if (agent.perks != null) {
            for (Integer lvl : agent.perks.values()) if (lvl != null) perksSum += lvl;
        }
        stats.finalPerksSpent = perksSum;
        // Did the agent ever sight stairs on the level it ended on? Walk the level
        // tiles for a STAIRS_DOWN that's marked explored / visible (or fall back
        // to the agent's MobMemory copy).
        Level here = world.currentLevel();
        com.bjsp123.rl2.model.Point stairsHere = null;
        if (here != null) {
            for (int y = 0; y < here.height && stairsHere == null; y++) {
                for (int x = 0; x < here.width && stairsHere == null; x++) {
                    if (here.tiles[x][y] == com.bjsp123.rl2.model.Tile.STAIRS_DOWN) {
                        stairsHere = new com.bjsp123.rl2.model.Point(x, y);
                    }
                }
            }
        }
        if (stairsHere != null && agent.position != null) {
            stats.stairsReachableAtEnd =
                    com.bjsp123.rl2.logic.Pathfinder.nextStep(here, agent, stairsHere) != null;
            // Read the SMART agent's own per-mob knownTiles (level.explored
            // tracks the player FOV, which doesn't update for behavior=SMART).
            com.bjsp123.rl2.ai.MobMemory mem = com.bjsp123.rl2.ai.SmartAi.peekMemory(agent);
            // mem.knownTiles is sized for whatever level the memory was last
            // refreshed on. If the agent transitioned to a different-sized
            // level (e.g. chasm-fell into a BIGLEVEL) the array size won't
            // match `here.width`/`here.height` - clamp the iteration so we
            // don't IOOB inside the final stats dump.
            int memW = mem != null && mem.knownTiles != null
                    ? mem.knownTiles.length : 0;
            int memH = memW > 0 ? mem.knownTiles[0].length : 0;
            int sx = stairsHere.tileX(), sy = stairsHere.tileY();
            stats.stairsKnownAtEnd = mem != null && mem.knownTiles != null
                    && sx < memW && sy < memH
                    && mem.knownTiles[sx][sy];
            // Bonus diagnostic: log known fraction for the end-level so we can
            // see how much was actually mapped.
            if (mem != null && mem.knownTiles != null) {
                int known = 0, total = 0;
                int w = Math.min(here.width, memW);
                int h = Math.min(here.height, memH);
                for (int y = 0; y < h; y++) {
                    for (int x = 0; x < w; x++) {
                        com.bjsp123.rl2.model.Tile t = here.tiles[x][y];
                        if (t != com.bjsp123.rl2.model.Tile.FLOOR
                                && t != com.bjsp123.rl2.model.Tile.FLOOR_WOOD
                                && t != com.bjsp123.rl2.model.Tile.FLOOR_SPECIAL) continue;
                        total++;
                        if (mem.knownTiles[x][y]) known++;
                    }
                }
                stats.endLevelKnownFraction = total == 0 ? 0.0 : known / (double) total;
            }
        }
    }

    /** Compute the same per-tick state the trace writer uses and forward it
     *  to the stuck telemetry. Cheap enough at autoplay scale — the BFS
     *  helpers cache per-level data. Guards against the mob-memory size
     *  trailing the current level on cross-level transitions (chasm fall
     *  into a BIGLEVEL, scatter to a differently-sized level) - the
     *  exploration helpers IOOB when the memory's knownTiles is smaller
     *  than the level. SmartAi.run will resize memory on its next tick. */
    private void recordStuckTick(Level cur) {
        com.bjsp123.rl2.ai.MobMemory mem = com.bjsp123.rl2.ai.SmartAi.peekMemory(agent);
        if (mem != null && mem.knownTiles != null
                && (mem.knownTiles.length < cur.width
                        || (mem.knownTiles.length > 0
                                && mem.knownTiles[0].length < cur.height))) {
            // Memory is for a smaller level; skip this tick's telemetry.
            // Next tick the SmartAi brain runs and reshapes memory to
            // the new level dimensions.
            stuck.onTick(turnsElapsed, world.currentLevelIndex, 0.0,
                    null, null, null, cur.stairsDown,
                    com.bjsp123.rl2.ai.Decider.LAST_BRANCH.get(), lastStepName);
            return;
        }
        double knownFrac = mem == null
                ? 0.0
                : 1.0 - com.bjsp123.rl2.ai.eval.ExplorationEval.unexploredFraction(cur, mem);
        Point exploreT = mem == null
                ? null
                : com.bjsp123.rl2.ai.eval.ExplorationEval.nearestExploreTarget(agent, cur, mem);
        Point bfsToFront = exploreT == null
                ? null
                : com.bjsp123.rl2.ai.eval.ExplorationEval.nextStepToTarget(agent, cur, mem, exploreT);
        Point bfsToStairs = cur.stairsDown == null
                ? null
                : com.bjsp123.rl2.ai.eval.ExplorationEval.nextStepToTarget(agent, cur, mem, cur.stairsDown);
        String branch = com.bjsp123.rl2.ai.Decider.LAST_BRANCH.get();
        stuck.onTick(turnsElapsed, world.currentLevelIndex, knownFrac,
                exploreT, bfsToFront, bfsToStairs, cur.stairsDown,
                branch, lastStepName);
    }

    private String lastStepName = "-";

    private void observeEvents(Level cur) {
        if (cur.events == null) return;
        int depthIdx = world.currentLevelIndex;
        // Snapshot before iterating - downstream handlers may mutate level.events.
        GameEvent[] snap = cur.events.toArray(new GameEvent[0]);
        for (GameEvent ev : snap) {
            if (stuck != null) stuck.onEvent(turnsElapsed, ev);
            if (eventsWriter != null) writeEvent(ev, depthIdx);
            if (ev instanceof GameEvent.ItemPickedUp p) {
                if (p.picker() == agent && p.item() != null) {
                    stats.bumpItem(p.item().type, depthIdx);
                }
            } else if (ev instanceof GameEvent.MobKilled k) {
                if (k.mob() == null) continue;
                String type = k.mob().mobType;
                boolean byAgent = k.killer() == agent;
                stats.bumpKill(type, depthIdx, byAgent);
                // Death-cause attribution: when the agent itself dies, record
                // the killer's mob type (or "ENV" for environmental). Lets the
                // regression report tell us "agent died to ENEMY_PLAYER_ROGUE
                // N times" alongside the cumulative-damage breakdown.
                if (k.mob() == agent) {
                    if (k.killer() != null && k.killer().mobType != null) {
                        stats.deathCause = k.killer().mobType;
                    } else {
                        stats.deathCause = "ENV";
                    }
                }
            } else if (ev instanceof GameEvent.ItemThrown t) {
                if (t.thrower() == agent && t.item() != null
                        && t.item().inventoryCategory == com.bjsp123.rl2.model.Item.InventoryCategory.BOMB) {
                    stats.bombsThrown++;
                }
            } else if (ev instanceof GameEvent.WandMissileFired w) {
                if (w.caster() == agent) stats.wandsFired++;
            } else if (ev instanceof GameEvent.WandRayFired w) {
                if (w.caster() == agent) stats.wandsFired++;
            } else if (ev instanceof GameEvent.MagicMissileFired m) {
                // Player-fired magic missile wand also lands here.
                if (m.caster() == agent) stats.wandsFired++;
            } else if (ev instanceof GameEvent.MobMeleeAttacked m) {
                if (m.attacker() == agent) {
                    stats.meleeAttacks++;
                    if (m.dealt() > 0) stats.meleeDamage += m.dealt();
                }
            } else if (ev instanceof GameEvent.DamageDealt d) {
                // Outgoing damage: classify wand / bomb by the cause's
                // originating item. Melee damage is already captured from
                // MobMeleeAttacked above; skipping it here avoids
                // double-counting.
                if (d.source() == agent && d.cause() != null
                        && d.cause().originItem() != null) {
                    com.bjsp123.rl2.model.Item.InventoryCategory cat =
                            d.cause().originItem().inventoryCategory;
                    if (cat == com.bjsp123.rl2.model.Item.InventoryCategory.WAND) {
                        stats.wandDamage += d.amount();
                    } else if (cat == com.bjsp123.rl2.model.Item.InventoryCategory.BOMB) {
                        stats.bombDamage += d.amount();
                    }
                }
                // Incoming damage: bucket by cause.medium (mechanism) and
                // by source-mob type (who hit me) so the harness can show
                // where HP is leaking.
                if (d.target() == agent && d.amount() > 0) {
                    stats.damageTaken += d.amount();
                    String medium = "unknown";
                    String src    = "ENV";
                    if (d.cause() != null) {
                        if (d.cause() == com.bjsp123.rl2.logic.MobSystem.DamageCause.NONE) {
                            medium = "environment";
                        } else if (d.cause().medium() != null
                                && !d.cause().medium().isEmpty()) {
                            medium = d.cause().medium();
                        }
                        if (d.cause().origin() != null && d.cause().origin().mobType != null) {
                            src = d.cause().origin().mobType;
                        }
                    }
                    stats.damageTakenByMedium.merge(medium, d.amount(), Integer::sum);
                    stats.damageTakenBySource.merge(src,    d.amount(), Integer::sum);
                }
            } else if (ev instanceof GameEvent.HealApplied h) {
                // HealApplied fires when a potion's REGEN tick lands - imperfect
                // proxy for "drinks". Better signal: ItemUsed events, but none of
                // those distinguish potion vs other uses cleanly. Count distinct
                // application events as a rough drink-count.
                if (h.mob() == agent && h.amount() > 0) stats.potionsDrunk++;
            }
        }
        cur.events.clear();
    }

    private void observeStairs() {
        int now = world.currentLevelIndex;
        if (now != lastLevelIndex) {
            if (now > lastLevelIndex) stats.stairsDescended++;
            else                      stats.stairsAscended++;
            if (now > stats.depthReached) stats.depthReached = now;
            if (now >= 0 && now < stats.arrivalTickPerDepth.length
                    && stats.arrivalTickPerDepth[now] < 0) {
                stats.arrivalTickPerDepth[now] = turnsElapsed; // first arrival at this depth
            }
            lastLevelIndex = now;
        }
    }

    private static Point pickSpawn(Level start, Random rng) {
        // Each candidate must be a walkable tile AND pathfind to stairsDown -
        // otherwise the run can't even possibly terminate via descend, and we'd
        // be back to TIMEOUTs on isolated spawn pockets.
        if (isValidSpawn(start, start.spawnPoint)) return start.spawnPoint;
        if (isValidSpawn(start, start.stairsUp))   return start.stairsUp;
        for (int tries = 0; tries < 1000; tries++) {
            int x = 1 + rng.nextInt(start.width - 2);
            int y = 1 + rng.nextInt(start.height - 2);
            Tile t = start.tiles[x][y];
            if (t != Tile.FLOOR && t != Tile.FLOOR_WOOD && t != Tile.FLOOR_SPECIAL) continue;
            Point p = new Point(x, y);
            if (isValidSpawn(start, p)) return p;
        }
        // Last resort - any floor (run is likely unwinnable from here but at least
        // the agent has something to stand on).
        for (int tries = 0; tries < 500; tries++) {
            int x = 1 + rng.nextInt(start.width - 2);
            int y = 1 + rng.nextInt(start.height - 2);
            if (start.tiles[x][y] == Tile.FLOOR) return new Point(x, y);
        }
        return new Point(start.width / 2, start.height / 2);
    }

    private static boolean isValidSpawn(Level level, Point p) {
        if (p == null) return false;
        Tile t = level.tiles[p.tileX()][p.tileY()];
        if (t.blocksMovement()) return false;
        if (level.stairsDown == null) return true;
        return canReach(level, p, level.stairsDown);
    }

    /** Quick spawn-time connectivity check using a throwaway player mob with
     *  faction=PLAYER so the SMART-equivalent traversal rules apply. */
    private static boolean canReach(Level level, Point from, Point to) {
        Mob probe = new Mob();
        probe.behavior = Mob.Behavior.PLAYER;
        probe.isPlayer = true;
        probe.faction = "PLAYER";
        probe.position = from;
        return com.bjsp123.rl2.logic.Pathfinder.nextStep(level, probe, to) != null;
    }

    public static int defaultTickBudget() {
        return 2_000_000;
    }

    public static int worldWidth()  { return GameBalance.LEVEL_BASE_W; }
    public static int worldHeight() { return GameBalance.LEVEL_BASE_H; }
}
